services:
  gitlab-runner:
    image: gitlab/gitlab-runner:${VERSION}
    container_name: gitlab-runner
    restart: always
    environment:
      TZ: ${TZ}
    volumes:
      - ./config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock