services:
  nexus:
    image: sonatype/nexus3:${VERSION}
    container_name: nexus
    restart: always
    stop_grace_period: 120s
    ports:
      - "${HTTP_PORT}:8081"
      - "${PROXY_PORT}:5000"
      - "${HOSTED_PORT}:5001"
    volumes:
      - ./data:/nexus-data