stages:
  - test
  - build

variables:
  # Настройки
  REGISTRY_URL: "192.168.31.136:5001"
  PROXY_REGISTRY: "192.168.31.136:5000"
  DOCKER_IMAGE: "example-go-app"
  DOCKERFILE: "Dockerfile.multistage"

  # Прокси для GO
  GOPROXY: "http://192.168.31.136:8081/repository/go-proxy/"

test:
  stage: test
  image: $PROXY_REGISTRY/golang:1.19
  script:
    - go mod download
    - go test -v -race ./...

build:
  stage: build
  image: $PROXY_REGISTRY/docker:27.5.1

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY_URL
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $PROXY_REGISTRY

  script:
    - docker build --build-arg GOPROXY=$GOPROXY --pull --rm -f $DOCKERFILE -t $REGISTRY_URL/$DOCKER_IMAGE:latest .
    - docker tag $REGISTRY_URL/$DOCKER_IMAGE:latest $REGISTRY_URL/$DOCKER_IMAGE:$CI_COMMIT_SHA

    - echo "push в Docker"
    - docker push $REGISTRY_URL/$DOCKER_IMAGE:latest
    - docker push $REGISTRY_URL/$DOCKER_IMAGE:$CI_COMMIT_SHA

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

