services:
  gitlab:
    image: gitlab/gitlab-ce:${VERSION}
    container_name: gitlab
    restart: unless-stopped
    hostname: ${HOSTNAME}
    environment:
      TZ: ${TZ}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${HOSTNAME}:${HTTP_PORT}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${SSH_PORT}
    ports:
      - "${HTTP_PORT}:80"
      - "${SSH_PORT}:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
    healthcheck:
      disable: ${HEALTHCHECK_DISABLE}
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3