---
- name: Deploy Common Configuration and Docker
  hosts: all
  become: true
  roles:
    - role: common
    - role: geerlingguy.docker
  tags:
    - always


- name: Install Nexus Repository Manager
  hosts: nexus
  become: true
  collections:
     - cloudkrafter.nexus
  roles:
    - role: nexus

- name: Install GitLab
  hosts: gitlab
  become: true
  roles:
    - role: gitlab
  tags:
    - always

- name: Install GitLab Runners
  hosts: gitlab_runners
  become: true
  roles:
    - role: gitlab_runner
  tags:
    - always