---
- name: Create GitLab directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ gitlab_config_path }}"
    - "{{ gitlab_logs_path }}"
    - "{{ gitlab_data_path }}"
    - "{{ gitlab_install_path }}"

- name: Template docker-compose file for GitLab
  template:
    src: gitlab-docker-compose.yml.j2
    dest: "{{ gitlab_install_path }}/docker-compose.yml"
    mode: '0644'

- name: Start GitLab container (wait)
  community.docker.docker_compose_v2:
    project_src: "{{ gitlab_install_path }}"
    state: present

- name: Wait for GitLab to become available
  uri:
    url: "http://localhost:{{ gitlab_http_port }}/users/sign_in"
    status_code: 200
  register: gitlab_status
  until: gitlab_status.status == 200
  retries: 40
  delay: 10
  changed_when: false